apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: iot-pipeline
  labels:
    app.kubernetes.io/name: backend-consumer
    app.kubernetes.io/component: backend
data:
  PORT: "8080"
  AWS_REGION: "us-east-1"
  MONGO_URI: "mongodb://mongodb-service:27017/iot_db"
