apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: iot-pipeline
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      name: http-web
  selector:
    app.kubernetes.io/name: grafana
